### ISSUE TITLE
JSErrorCollector is broken with webdriver 2.45.0 and Firefox 36

### ISSUE THREAD

**Issue by tporeba** [mguillem/JSErrorCollector#19]
I get following error after updating to webdriver 2.45.0 and Firefox 36:

> org.openqa.selenium.WebDriverException: Exposing privileged or cross-origin callable is prohibited
Command duration or timeout: 31 milliseconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'TPOREBA-W', ip: '10.10.8.47', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_10'
Session ID: c0dc3661-9622-47c9-88af-566e20a25e9a
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=36.0}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:508)
	at net.jsourcerer.webdriver.jserrorcollector.JavaScriptError.readErrors(JavaScriptError.java:135)

It seems new Firefox doesn't like the script from `JavaScriptError.readErrors` line 134:
    return window.JSErrorCollector_errors ? window.JSErrorCollector_errors.pump() : []

**Comment by joelthedrummer** [comment]
I get the same error.  I was going to look into this sometime, but haven't had a chance yet.

**Comment by joelthedrummer** [comment]
Some hints I found here - https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1426581 - it looks like the Firefox extension may need to change how JSErrorCollector_errors works.  Need to research this more to understand how it all works still.

**Comment by tporeba** [comment]
This is the first time I work with some FF plugins, but somehow I managed to get it back online, see pull request:
https://github.com/mguillem/JSErrorCollector/pull/20

**Comment by tporeba** [comment]
Just in case somebody needs...
 - built dist version: https://github.com/mguillem/JSErrorCollector/pull/21
 - (almost) working Junits: https://github.com/mguillem/JSErrorCollector/pull/22

**Comment by excid3** [comment]
Thanks @tporeba, that worked for me. :+1:

**Comment by p-run** [comment]
We are having the same issue, #21 fixes it.

**Comment by mguillem** [comment]
Pull requests included and improved. Thanks
